### ISSUE TITLE
关于事件订阅的回复

### ISSUE THREAD

**Issue by Wlndy** [Yancy1028/Jusoft.DingtalkStream#3]
你好！ 我想问下我用最新的代码，回复消息后  依然会再次推送细信息。。应该是没有回复成功。。

**Comment by Yancy1028** [comment]
没有回复成功？具体情况你还是细说一些。
你用的是代码还是nuget上下载的版本吗，那个会新一些。
github代码上传我这边可能会延迟一些。
另外你要不然加我钉钉：yinpengai

**Comment by Yancy1028** [comment]
不建议在回调处理程序中处理耗时的业务，建议接收到数据后尽快存储下来，并交于其他程序进行处理。
钉钉默认接收消息回复的超时机制为10s，30s，60s，120s。
