### ISSUE TITLE
机器人流式对话【打印机模式】

### ISSUE THREAD

**Issue by KiisMyGun** [Yancy1028/Jusoft.DingtalkStream#4]
机器人stream现在不可以一个消息流式回答，一个字一个字往外蹦，钉钉客户端Bot回答像打印机一样输出
所以，需要通过 [ AI卡片流式更新](https://open.dingtalk.com/document/orgapp/api-streamingupdate?spm=a2q3p.21071111.0.0.371f1cfaVmKpe7) 实现。

有计划纳入SDK吗？

**Comment by Yancy1028** [comment]
这个如果钉钉那边针对Stream模式下没支持的话，我的SDK内部也没法去实现的。
目前Stream的SDK 内部我是尽可能先避免了调用开放平台API去生成access_token的动作。
像 [AI卡片流式更新](https://open.dingtalk.com/document/orgapp/api-streamingupdate?spm=a2q3p.21071111.0.0.371f1cfaVmKpe7) 也是基于开放平台去调用的，对我来说除非钉钉那边Stream 先支持，我这边才能支持。

**Comment by KiisMyGun** [comment]
好吧，钉钉暂时没有计划做这个事情

**Comment by gaoconggit** [comment]
https://github.com/zfanswer/dify-on-dingtalk
---
参考这样可以实现吗？

**Comment by Yancy1028** [comment]
> ## https://github.com/zfanswer/dify-on-dingtalk
> 参考这样可以实现吗？

为啥不考虑直接使用AI助理来实现编排的内容？还是希望说通过stream 来处理收到的机器人消息的回复动作么
